In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.3, random_state = 4)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
# X_train_count.toarray()
X_train_count.toarray()[:2]

# v.get_feature_names()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [8]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [9]:
X_test_count = v.transform(X_test)

model.score(X_test_count, y_test)

0.9796650717703349

In [10]:
v1 = CountVectorizer()

X_test_count = v1.fit_transform(X_test)

model.fit(X_test_count,y_test)

model.score(X_test_count, y_test)

0.9964114832535885

In [11]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [12]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [13]:
clf.score(X_test,y_test)

0.9796650717703349

In [14]:
clf.predict(emails)

array([0, 1])

In [15]:
X = df.Message
y = df.spam

In [16]:
v2 = CountVectorizer()
X_count = v2.fit_transform(X.values)

In [17]:
model = MultinomialNB()
model.fit(X_count,y)

MultinomialNB()

In [18]:
pred = model.predict(X_count)
pred

array([0, 0, 1, ..., 0, 0, 0])

In [19]:
# model.score(X_count, y)

In [20]:
from joblib import dump, load

dump(model, 'naive_bayes.joblib')

['naive_bayes.joblib']

In [21]:
loaded_model = load('naive_bayes.joblib')

In [22]:
x_new = [
    'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&Cs apply 08452810075over18'
]

In [23]:
# x_new = np.array(x_new)

In [24]:
x_new_count = v2.transform(x_new)

x_new_count

<1x8709 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [25]:
more_preds  = loaded_model.predict(x_new_count)
more_preds

array([1])