In [1]:
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('cancer_data.csv')
print(df.shape)
df.head()

(699, 11)


ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [3]:
df = df[pd.to_numeric(df['BareNuc'], errors='coerce').notnull()]
df['BareNuc'] = df['BareNuc'].astype('int')
df.dtypes

ID             int64
Clump          int64
UnifSize       int64
UnifShape      int64
MargAdh        int64
SingEpiSize    int64
BareNuc        int64
BlandChrom     int64
NormNucl       int64
Mit            int64
Class          int64
dtype: object

In [4]:
df.count()

ID             683
Clump          683
UnifSize       683
UnifShape      683
MargAdh        683
SingEpiSize    683
BareNuc        683
BlandChrom     683
NormNucl       683
Mit            683
Class          683
dtype: int64

In [5]:
X = df.drop(['Class','ID'], axis=1)
y = df['Class']

# print(y.head())
# X.head()

In [6]:
model = SVC()

model.fit(X, y_train)

SVC()

In [7]:
y_pred = model.predict(X)

accuracy_score(y,y_pred)

0.9765739385065886

In [8]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)
X_scaled[5]

array([0.77777778, 1.        , 1.        , 0.77777778, 0.66666667,
       1.        , 0.88888889, 0.66666667, 0.        ])

In [9]:
vector = SVC()

vector.fit(X_scaled, y)

SVC()

In [10]:
y_pred_new = vector.predict(X_scaled)

accuracy_score(y,y_pred_new)

0.9765739385065886

In [11]:
from joblib import dump, load

dump(model, 'svm.joblib')

['svm.joblib']

In [12]:
loaded_model = load('svm.joblib')

In [13]:
x_real = np.array([8,10,10,8,7,10,9,7,1]).reshape(1,-1)

In [14]:
x_real_process = scaler.transform(x_real)
x_real_process

array([[0.77777778, 1.        , 1.        , 0.77777778, 0.66666667,
        1.        , 0.88888889, 0.66666667, 0.        ]])

In [15]:
new_model = loaded_model.predict(x_real_process)
new_model

array([2])